baseurl = "https://seangraham.io/"
languageCode = "en-US"
title = "Sean Graham"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.jpg"
  author = "Sean Graham"
  description = ""

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "cavemangraham"
  Email         = "seangraham@protonmail.com"
  Twitter       = "cavemangraham"
  LinkedIn      = "sean-graham-13227b7a"
  Stackoverflow = ""
  Medium        = ""
  Telegram      = ""

## Main Menu
[[menu.main]]
  name = "articles"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "resources"
  identifier = "resources"
  weight = 200
  url = "/resources"
