---
upload_path: "/static/uploads/"
frontmatter_file_url_template: "/static/uploads/"
body_file_url_template: "/static/uploads/"
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections: 
version: 0.37.1
