---
label: default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- content/posts/onward-travel-solved.md
- content/posts/what-i-learned-from-6-months-on-the-road.md
- content/posts/my-static-stack-jekyll-netlify-forestry.md
- content/posts/honest-review-of-remarkable-tablet.md
- content/posts/guns-germs-and-steel.md
- content/contact.md
- content/posts/the-good--the-bad--and-the-ugly-of-the-amazon-echo.md
- content/resources.md
